# Generated by Django 5.0.6 on 2024-07-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_conversation_payment_status_conversation_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='payment_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
