# Generated by Django 5.0.6 on 2024-06-23 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_remove_progofer_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='duration',
        ),
    ]
