# Generated by Django 5.0.6 on 2024-05-31 14:45

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
        ('transaction', '0002_initial'),
        ('user', '0002_alter_customuser_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Mon', 'Mon'), ('Tues', 'Tues'), ('Wed', 'Wed'), ('Thur', 'Thur'), ('Fri', 'Fri'), ('Sat', 'Sat'), ('Sun', 'Sun')], max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ErrandBoy',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('owns_bike', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('00:00', '00:00'), ('01:00', '01:00'), ('02:00', '02:00'), ('03:00', '03:00'), ('04:00', '04:00'), ('05:00', '05:00'), ('06:00', '06:00'), ('07:00', '07:00'), ('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00'), ('22:00', '22:00')], max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='wallet',
            name='transaction_pin',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_code', models.CharField(max_length=10, unique=True)),
                ('contract_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pay_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contract_length', models.IntegerField()),
                ('start_date', models.DateField(default=datetime.date(2024, 5, 31))),
                ('end_date', models.DateField()),
                ('days_remaining', models.IntegerField(default=0)),
                ('contract_status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Settled', 'Settled'), ('Declined', 'Declined'), ('Terminated', 'Terminated')], default='Pending', max_length=20)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gofer_or_errandBoy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('duration', models.IntegerField(null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.day')),
                ('from_hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_hour', to='transaction.hours')),
                ('gofer_or_errandBoy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_schedules', to='transaction.errandboy')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='main.subcategory')),
                ('to_hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_hour', to='transaction.hours')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day__created_at', 'from_hour__created_at'],
                'unique_together': {('user', 'gofer_or_errandBoy', 'day', 'from_hour', 'to_hour')},
            },
        ),
    ]
