# Generated by Django 5.0.6 on 2024-06-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='recipient_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
