# Generated by Django 5.0.6 on 2024-06-26 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_initial'),
        ('user', '0002_alter_progofer_custom_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='pro_gofer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='user.progofer'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('pro_gofer', 'day', 'from_hour', 'to_hour'), name='unique_schedule'),
        ),
    ]
