# Generated by Django 5.0.6 on 2024-06-23 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_remove_schedule_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='user',
            new_name='custom_user',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='custom_user',
        ),
        migrations.RenameField(
            model_name='progofer',
            old_name='user',
            new_name='custom_user',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='user',
            new_name='custom_user',
        ),
    ]
