# Generated by Django 5.0.6 on 2024-06-10 08:05

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_day_errandboy_hours_wallet_transaction_pin_contract_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='gofer_or_errandBoy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='service_type',
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 6, 10)),
        ),
        migrations.AlterField(
            model_name='hours',
            name='name',
            field=models.CharField(choices=[('00:00', '00:00'), ('01:00', '01:00'), ('02:00', '02:00'), ('03:00', '03:00'), ('04:00', '04:00'), ('05:00', '05:00'), ('06:00', '06:00'), ('07:00', '07:00'), ('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00'), ('22:00', '22:00'), ('23:00', '23:00')], max_length=10, unique=True),
        ),
        migrations.DeleteModel(
            name='ErrandBoy',
        ),
    ]
