# Generated by Django 5.0.6 on 2024-06-10 08:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_alter_schedule_gofer_or_errandboy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
