# Generated by Django 5.0.6 on 2024-06-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_schedule_maximum_bookings_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='maximum_bookings',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
    ]
