# Generated by Django 5.0.6 on 2024-06-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_alter_schedule_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duration (optional)'),
        ),
    ]
