# Generated by Django 5.0.7 on 2024-07-19 14:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_stripecustomer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StripeCustomer',
            new_name='StripeUser',
        ),
    ]
