# Generated by Django 5.0.7 on 2024-07-24 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_delete_booking'),
        ('transaction', '0007_alter_stripeuser_user'),
    ]

    operations = [
    ]
