# Generated by Django 5.0.6 on 2024-06-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_reviews_comment_alter_reviews_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('id_card', 'ID Card'), ('international_passport', 'International Passport'), ('drivers_license', 'Drivers License'), ('utility_bill', 'Utility Bill'), ('nin', 'NIN'), ('cac', 'CAC')], max_length=50),
        ),
    ]
