# Generated by Django 5.0.6 on 2024-06-19 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_contract_custom_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
