# Generated by Django 5.0.6 on 2024-06-21 13:35

import django.core.validators
import django.db.models.deletion
import main.validate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_contract'),
        ('user', '0004_remove_gofer_is_on_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='user',
        ),
        migrations.AddField(
            model_name='reviews',
            name='message_poster',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to='user.messageposter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ErrandBoyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('ssn', 'SSN'), ('nin', 'NIN')], max_length=5)),
                ('document_number', models.CharField(max_length=11, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('errand_boy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='user.errandboy')),
            ],
        ),
        migrations.CreateModel(
            name='GoferDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('ssn', 'SSN'), ('nin', 'NIN')], max_length=5)),
                ('document_number', models.CharField(max_length=11, unique=True)),
                ('document_of_expertise', models.FileField(upload_to='main/documents', validators=[main.validate.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'pdf'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('gofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='user.gofer')),
            ],
        ),
        migrations.CreateModel(
            name='VendorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('ssn', 'SSN'), ('nin', 'NIN')], max_length=5)),
                ('document_number', models.CharField(max_length=11, unique=True)),
                ('document_of_expertise', models.FileField(upload_to='main/documents', validators=[main.validate.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'pdf'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='user.vendor')),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
