# Generated by Django 5.0.6 on 2024-06-04 01:29

import django.core.validators
import main.validate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_document_document_owner_alter_reviews_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='main/documents', validators=[main.validate.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
