# Generated by Django 5.0.6 on 2024-06-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_document_file_alter_subcategory_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document_owner',
            new_name='custom_user',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='file',
            new_name='document_of_expertise',
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('bvn', 'BVN'), ('nin', 'NIN')], max_length=5),
        ),
    ]
