# Generated by Django 5.0.6 on 2024-06-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_document_owner_document_custom_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_number',
            field=models.CharField(default=12345678901, max_length=11),
            preserve_default=False,
        ),
    ]
