# Generated by Django 5.0.6 on 2024-06-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_progofer_custom_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='progofer',
            name='maximum_bookings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
