# Generated by Django 5.0.7 on 2024-07-16 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_address_house_number'),
        ('user', '0002_remove_media_gofer_media_vendor_alter_media_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='category',
        ),
        migrations.AddField(
            model_name='vendor',
            name='sub_category',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_subcategory', to='main.subcategory'),
            preserve_default=False,
        ),
    ]
