<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-06-05 08:56

=======
# Generated by Django 5.0.6 on 2024-06-01 18:32

import django.db.models.deletion
from django.conf import settings
>>>>>>> 00552d0 (Verify phone number functionality)
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='files/dp'),
        ),
<<<<<<< HEAD
=======
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(max_length=6)),
                ('verification_expiry', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phone_verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
>>>>>>> 00552d0 (Verify phone number functionality)
    ]
