# Generated by Django 5.0.6 on 2024-06-10 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
        ('user', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gofer',
            name='location',
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gofer',
            name='mobility_means',
            field=models.CharField(choices=[('Bicycle', 'Bicycle'), ('Motorcycle', 'Motorcycle'), ('Car', 'Car'), ('Truck', 'Truck'), ('Van', 'Van'), ('Bus', 'Bus'), ('Other', 'Other')], default='Motorcycle', max_length=20),
        ),
        migrations.AlterField(
            model_name='errand',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Ongoing', 'Ongoing'), ('Terminated', 'Terminated')], default='O', max_length=20),
        ),
        migrations.CreateModel(
            name='ErrandBoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobility_means', models.CharField(choices=[('Bicycle', 'Bicycle'), ('Motorcycle', 'Motorcycle'), ('Car', 'Car'), ('Truck', 'Truck'), ('Van', 'Van'), ('Bus', 'Bus'), ('Other', 'Other')], default='Bicycle', max_length=20)),
                ('charges', models.IntegerField(default=0)),
                ('documents', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='errand_documents', to='main.document')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='errand_boy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
