# Generated by Django 5.0.6 on 2024-06-01 18:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_phone_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneverification',
            name='verification_expiry',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
