# Generated by Django 5.0.6 on 2024-06-19 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_messageposter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gofer',
            name='is_on_contract',
        ),
    ]
