# Generated by Django 5.0.6 on 2024-06-12 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_phone_verified_and_more'),
        ('user', '0003_remove_gofer_location_customuser_gender_and_more'),
    ]

    operations = [
    ]
