# Generated by Django 5.0.6 on 2024-06-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_progofer_maximum_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progofer',
            name='maximum_bookings',
            field=models.IntegerField(blank=True, default=500, null=True),
        ),
    ]
