# Generated by Django 5.0.6 on 2024-06-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_progofer_maximum_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progofer',
            name='maximum_bookings',
            field=models.IntegerField(blank=True, default=500),
        ),
    ]
