# Generated by Django 5.0.6 on 2024-06-01 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_phoneverification_verification_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneverification',
            name='verification_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 1, 19, 10, 46, 785014, tzinfo=datetime.timezone.utc)),
        ),
    ]
