# Generated by Django 5.0.6 on 2024-06-02 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_phoneverification_verification_expiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneVerification',
        ),
    ]
