# Generated by Django 5.0.7 on 2024-07-17 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_vendor_category_vendor_sub_category'),
        ('user', '0005_progofer_is_available_schedule'),
    ]

    operations = [
    ]
