# Generated by Django 5.0.7 on 2024-07-24 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_merge_20240717_1956'),
        ('user', '0009_errandboy_is_available_alter_gofer_is_available'),
    ]

    operations = [
    ]
