name: Deploy to EC2

on:
  push:
    branches:
      - CHIME
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to EC2
      run: |
        scp -r -o StrictHostKeyChecking=no - --exclude=.git/objects ./* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/testServer/goufer-api

    - name: SSH into EC2 and run commands
      run: |
          # Create a temporary tar archive excluding .git directory
          tar cf - --exclude=.git/objects . | ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'tar xf - -C /home/***/testServer/goufer-api'
          echo 'Syncing Push to CHIME'
          cd /home/ubuntu/testServer
          sudo systemctl restart nginx
          sudo service gunicorn restart
          # docker-compose down
          # docker-compose up -d
          echo "Success"
        EOF
